services:
  - type: web
    name: infant-cry-api
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app --workers 1 --timeout 120
    envVars:
      - key: PORT
        value: 10000
